settings:
  title: 'Yaacobi Status Page'
  url: 'https://status.yaacobi.in' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: authelia # unique identifier
    name: Authentication Portal
    description: 'Does Auth work?' # default=empty
    url: 'https://auth.yaacobi.in/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: traefik
    name: traefik
    description: 'Traefik Admin Panel'
    url: 'https://traefik.yaacobi.in/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: requestrr
    name: Requests
    url: 'https://requests.yaacobi.in/'
    method: GET
    followRedirect: true
    expectStatus: 200
